install:
  - rm -rf public || exit 0
# Build the website
script:
  - bin/hugo

after_script:
  - echo "$CNAME" > public/CNAME

after_success:
  - git commit -a -m "Committed by Travis-CI build number: $TRAVIS_JOB_ID"

# Deploy to GitHub pages
deploy:
  provider: pages
  repo: atts-group/atts-group.github.io
  target-branch: master
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  name: TravisCIBot
  on:
    branch: master
