language: go

before_script:
    - rm -rf public 2> /dev/null

# Build the website
script:
    - bin/hugo
    - echo "$CNAME" > public/CNAME

# Deploy to GitHub pages
deploy:
  provider: pages
  repo: atts-group/atts-group.github.io
  target-branch: master
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
