language: go

git:
    submodules: false

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install curl -y

before_script:
    - rm -rf public 2> /dev/null
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    
# Build the website
script:
    - bin/hugo
    - echo "$CNAME" > public/CNAME

notifications:
  webhooks:
    urls:
      - https://atts-webhook.herokuapp.com/notify/push_bear
    on_success: change # default: always
    on_failure: always # default: always
    on_start: never   # default: never
    on_cancel: never # default: always
    on_error: never # default: always

# Deploy to GitHub pages
deploy:
  provider: pages
  repo: atts-group/atts-group.github.io
  target-branch: master
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
