baseURL = "https://codenow.me/"
title = "ATTS"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
sectionPagesMenu = "main"

pygmentscodefences = true
pygmentsStyle = "tango" # "emacs" # "autumn" # "manni" # "friendly"
enableRobotsTXT = true

DefaultContentLanguage = "zh"

googleAnalytics = "UA-136313587-1"

[params]
	provider = "GitHub"
	repo_url = "https://github.com/atts-group/atts"
	author = "ATTS Group"
	copyright = "CC BY 4.0 License"
	logo = "images/logo.png"
	favicon = "images/favicon.png"

	# Theme color, available values are: red, pink, purple, deep-purple, indigo, blue, light-blue, cyan, teal, green, light-green, lime, yellow, amber, orange, deep-orange, brown, grey and blue-grey
	[params.palette]
		primary="indigo"

	[params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"
	
	
[social]
	github  = "atts-group"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[outputs]
	home = [ "HTML", "JSON"]
	page = [ "HTML", "JSON"]

