baseURL = "/"
title = "ATTS"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
sectionPagesMenu = "main" 
pygmentscodefences = true
pygmentsStyle = "tango" # "emacs" # "autumn" # "manni" # "friendly"


[params]
	[params.palette]
	primary="red"

	provider = "GitHub"
	repo_url = "https://github.com/atts-group/atts"
		
[outputs]
	home = [ "HTML", "JSON"]
	page = [ "HTML", "JSON"]

